import type { Metadata } from "next";
import { Lato, Playfair_Display } from "next/font/google";
import "../globals.css";
import { ForceLoad } from "@/components/loader";

// Heading
const playfairDisplay = Playfair_Display({
	variable: "--font-playfair-display",
	subsets: ["latin"],
});

// Body
const lato = Lato({
	variable: "--font-lato",
	subsets: ["latin"],
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${playfairDisplay.variable} ${lato.variable} h-full antialiased`}
		>
			<body className="min-h-screen bg-white overflow-hidden pointer-events-auto">
				{children}
				<ForceLoad />
			</body>
		</html>
	);
}
