/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/eye.glb 
*/

import { useGLTF } from "@react-three/drei";

const EYE_MODEL_URL = "/models/eye.glb";

export function Eye(props) {
  const { nodes } = useGLTF(EYE_MODEL_URL);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.geometry_0.geometry}
        material={nodes.geometry_0.material}
      />
    </group>
  );
}

useGLTF.preload(EYE_MODEL_URL);
