import type { Metadata } from 'next';
import { Playfair_Display, Roboto, Roboto_Mono } from 'next/font/google';
import './globals.css';
import { Theme } from './components/theme';

const playfairDisplay = Playfair_Display({
  variable: '--font-display',
  weight: '700',
  subsets: ['latin'],
});

const roboto = Roboto({
  variable: '--font-body',
  weight: '300',
  style: ['italic', 'normal'],
  subsets: ['latin'],
});

const robotoMono = Roboto_Mono({
  variable: '--font-mono',
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Theme />
      <body
        className={`${playfairDisplay.variable} ${roboto.variable} ${robotoMono.variable} min-h-screen overflow-hidden antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
